phase_1_parallel_base_training:
  configs:
  - config_variant_1_balanced.yaml
  - config_variant_2_wider.yaml
  - config_variant_3_deeper.yaml
  - optimization_configs/config_fast_convergence.yaml
  description: Train base models in parallel with different configs
  epochs: 20
  goal: Get diverse base models quickly
  parallel: true
phase_2_stability_training:
  configs:
  - optimization_configs/config_stable_training.yaml
  - optimization_configs/config_high_performance.yaml
  description: Train stable, longer models for robustness
  epochs: 30
  goal: Get high-quality robust models
  parallel: true
phase_3_fine_tuning:
  configs:
  - optimization_configs/config_finetune_stage2.yaml
  description: Fine-tune best models from previous phases
  epochs: 10
  goal: Polish best models for maximum performance
  parallel: false
  prerequisites: Best run_ids from phases 1&2
phase_4_ensemble:
  beam_search_tuning: true
  description: Create and validate ensemble
  goal: Achieve CER < 6%
  methods:
  - output_averaging
  - weight_averaging_equal
  - weight_averaging_performance
